- name: create jenkins jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    mjob:
      - { job_name: "payment" , repo_name: "https://github.com/sreedharm07/a-payment.git" }

    sjob:
     - { job_name: "dispatch" , repo_name: "https://github.com/sreedharm07/a-dispatch.git" }

