- name: create jenkins jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    mjob:
      - { job_name: "catalogue" , repo_name: "https://github.com/sreedharm07/a-catalogue.git" }

    sjob:
     - { job_name: "dispatch" , repo_name: "https://github.com/sreedharm07/a-dispatch.git" }

