- name: Copy  folder
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml


- name: Create a folder- {{ item.folder_name  }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{ item.folder_name  }}"
    password: admin123
    url: http://172.31.31.9:8080
    user: admin