- name: Copy file with owner and permissions
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml

- name: Create a jenkins job - {{ item.job_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mjob.xml') }}"
    name: "{{ item.job_name }}"
    password: admin123
    url: http://172.31.31.9:8080
    user: admin